/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Cliente;
import static classes.Cliente.listaClientes;
import classes.Funcionario;
import static classes.Funcionario.listaFuncionarios;
import classes.Gerente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static telas.cadastarGerente.listaGerente;
import static telas.cadastros.cadastrosFlag;

/**
 *
 * @author Yuri
 */
public class areaGerente extends javax.swing.JFrame {

    /**
     * Creates new form areaGerente
     */
    public areaGerente() {
        initComponents();
        
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);

        disableGerenteFields();
        disableControleFuncionariosButtons();
        disableControleFuncionariosFields();
        carregarTabelaFuncionario();
        carregarTabelaCliente();
        enableFuncionarioInfo();

        
        btnCancelarGerente.setEnabled(false);
        btnSalvarGerente.setEnabled(false);
        btnAlterarGerente.setEnabled(true);
        
        btnNovoFuncionario.setEnabled(true);
        //btnPesquisarFuncionario.setEnabled(true);
        loadGerenteInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void enableFuncionarioInfo(){
        txtNomeFuncionario.setEnabled(true);
        ftxCPFFuncionario.setEnabled(true);
        txtCodigoFuncionario.setEnabled(true);
        btnBuscarFuncionario.setEnabled(true);
    }
    
    public void loadGerenteInfo(){
        Gerente gerente1 = listaGerente.get(0);
        txtNomeGerente.setText(gerente1.getNome());
        ftxCPFGerente.setText(gerente1.getCPF());
        txtEmailGerente.setText(gerente1.getEmail());
        txtSenhaGerente.setText(gerente1.getSenha());
        txtIdGerente.setText(gerente1.getCadastroGerente());
    }
    
    //Carregar a tabela com os funcionários da lista
        private void carregarTabelaFuncionario() {
            DefaultTableModel modeloTabela = new DefaultTableModel(new Object[] {"Cod.Funcionário","Nome","CPF"},0);
            
            for(int i=0;i<listaFuncionarios.size();i++){
                Object linha[] = new Object[]{listaFuncionarios.get(i).getCadastroFuncionario(),
                                              listaFuncionarios.get(i).getNome(),
                                              listaFuncionarios.get(i).getCPF()};
                modeloTabela.addRow(linha);
                
            }
            //Tabela recebe modelo
            tblControleFuncionarios.setModel(modeloTabela);
            
            tblControleFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(3);
            tblControleFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblControleFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(14);
            
            
    }
        
        private void carregarTabelaCliente(){
            DefaultTableModel modeloTabelaCliente = new DefaultTableModel(new Object[] {"Cod.Cliente","Nome","CPF","Data Nascimento","Endereço"},0);
            
            for(int i=0;i<listaClientes.size();i++){
                Object linha[] = new Object[] {listaClientes.get(i).getIdCliente(),
                                               listaClientes.get(i).getNome(),
                                               listaClientes.get(i).getCPF(),
                                               listaClientes.get(i).getDataNascimento(),
                                               listaClientes.get(i).getEndereco()};
                modeloTabelaCliente.addRow(linha);
                
                
            }
            //Tabela recebe modelo de clientes
            tblControleClientes.setModel(modeloTabelaCliente);
            
            tblControleClientes.getColumnModel().getColumn(0).setPreferredWidth(3);
            tblControleClientes.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblControleClientes.getColumnModel().getColumn(2).setPreferredWidth(14);
            tblControleClientes.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblControleClientes.getColumnModel().getColumn(4).setPreferredWidth(100);


            
        }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblNomeGerente = new javax.swing.JLabel();
        lblCPFGerente = new javax.swing.JLabel();
        lblEmailGerente = new javax.swing.JLabel();
        lblSenhaGerente = new javax.swing.JLabel();
        lblIdGerente = new javax.swing.JLabel();
        txtNomeGerente = new javax.swing.JTextField();
        txtEmailGerente = new javax.swing.JTextField();
        txtSenhaGerente = new javax.swing.JTextField();
        txtIdGerente = new javax.swing.JTextField();
        ftxCPFGerente = new javax.swing.JFormattedTextField();
        lblAreaGerente = new javax.swing.JLabel();
        btnAlterarGerente = new javax.swing.JButton();
        btnSalvarGerente = new javax.swing.JButton();
        btnCancelarGerente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNomeFuncionario = new javax.swing.JLabel();
        lblCPFFuncionario = new javax.swing.JLabel();
        lblIdFuncionario = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        txtCodigoFuncionario = new javax.swing.JTextField();
        btnNovoFuncionario = new javax.swing.JButton();
        btnBuscarFuncionario = new javax.swing.JButton();
        ftxCPFFuncionario = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblControleFuncionarios = new javax.swing.JTable();
        btnSalvarFuncionario = new javax.swing.JButton();
        btnExcluirFuncionario = new javax.swing.JButton();
        lblControleFuncionarios = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblControleClientes = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblCPFCliente = new javax.swing.JLabel();
        lblCodigoCliente = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        btnNovoCliente = new javax.swing.JButton();
        btnSalvarCliente = new javax.swing.JButton();
        btnExluirCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblControleClientes = new javax.swing.JTable();
        txtCPFCliente = new javax.swing.JFormattedTextField();
        lblBackground = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Área do Gerente");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/rei64.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setFont(new java.awt.Font("Old London", 0, 48)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 10, 130, 60));

        jPanel1.setBackground(new java.awt.Color(211, 181, 143));

        lblNomeGerente.setFont(new java.awt.Font("Old London", 0, 36)); // NOI18N
        lblNomeGerente.setText("Nome");

        lblCPFGerente.setFont(new java.awt.Font("Old London", 0, 36)); // NOI18N
        lblCPFGerente.setText("CPF");

        lblEmailGerente.setFont(new java.awt.Font("Old London", 0, 36)); // NOI18N
        lblEmailGerente.setText("E-mail");

        lblSenhaGerente.setFont(new java.awt.Font("Old London", 0, 36)); // NOI18N
        lblSenhaGerente.setText("Senha");

        lblIdGerente.setFont(new java.awt.Font("Old London", 0, 36)); // NOI18N
        lblIdGerente.setText("Id Gerente");

        txtNomeGerente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomeGerente.setToolTipText("insira o nome");
        txtNomeGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeGerenteActionPerformed(evt);
            }
        });

        txtEmailGerente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmailGerente.setToolTipText("insira o e-mail");

        txtSenhaGerente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSenhaGerente.setToolTipText("defina uma senha");

        txtIdGerente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdGerente.setToolTipText("defina um Id Gerente");

        try {
            ftxCPFGerente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxCPFGerente.setToolTipText("insira o CPF");
        ftxCPFGerente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblAreaGerente.setFont(new java.awt.Font("Old London", 0, 48)); // NOI18N
        lblAreaGerente.setText("Dados do Gerente");

        btnAlterarGerente.setBackground(new java.awt.Color(255, 255, 0));
        btnAlterarGerente.setFont(new java.awt.Font("Old London", 1, 24)); // NOI18N
        btnAlterarGerente.setText("Alterar");
        btnAlterarGerente.setToolTipText("alterar os dados já existentes");
        btnAlterarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarGerenteActionPerformed(evt);
            }
        });

        btnSalvarGerente.setBackground(new java.awt.Color(0, 255, 0));
        btnSalvarGerente.setFont(new java.awt.Font("Old London", 1, 24)); // NOI18N
        btnSalvarGerente.setText("Salvar");
        btnSalvarGerente.setToolTipText("Salvar os dados");
        btnSalvarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarGerenteActionPerformed(evt);
            }
        });

        btnCancelarGerente.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelarGerente.setFont(new java.awt.Font("Old London", 1, 24)); // NOI18N
        btnCancelarGerente.setText("Cancelar");
        btnCancelarGerente.setToolTipText("Cancelar a operação");
        btnCancelarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarGerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblEmailGerente)
                .addGap(209, 209, 209))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenhaGerente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmailGerente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ftxCPFGerente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeGerente)
                    .addComponent(txtIdGerente))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblAreaGerente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lblIdGerente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAlterarGerente)
                        .addGap(136, 136, 136)
                        .addComponent(btnSalvarGerente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btnCancelarGerente)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNomeGerente)
                                .addGap(215, 215, 215))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCPFGerente)
                                .addGap(220, 220, 220))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSenhaGerente)
                                .addGap(220, 220, 220))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAreaGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCPFGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxCPFGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmailGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenhaGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIdGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 530, 670));

        jPanel2.setBackground(new java.awt.Color(211, 181, 143));

        lblNomeFuncionario.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        lblNomeFuncionario.setText("Nome");

        lblCPFFuncionario.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        lblCPFFuncionario.setText("CPF");

        lblIdFuncionario.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        lblIdFuncionario.setText("Código de funcionário");

        txtNomeFuncionario.setToolTipText("insira o nome do funcionario");

        txtCodigoFuncionario.setToolTipText("insira o código do funcionário");
        txtCodigoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoFuncionarioActionPerformed(evt);
            }
        });

        btnNovoFuncionario.setBackground(new java.awt.Color(51, 255, 153));
        btnNovoFuncionario.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        btnNovoFuncionario.setText("Novo");
        btnNovoFuncionario.setToolTipText("Adicionar novo funcionário");
        btnNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFuncionarioActionPerformed(evt);
            }
        });

        btnBuscarFuncionario.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        btnBuscarFuncionario.setText("Buscar");
        btnBuscarFuncionario.setToolTipText("Buscar pelo funcionário");
        btnBuscarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFuncionarioActionPerformed(evt);
            }
        });

        try {
            ftxCPFFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxCPFFuncionario.setToolTipText("insira o CPF do funcionário");

        tblControleFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cód. Funcionário", "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblControleFuncionarios.setToolTipText("Tabela com os dados de funcionários");
        tblControleFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblControleFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblControleFuncionarios);
        if (tblControleFuncionarios.getColumnModel().getColumnCount() > 0) {
            tblControleFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(3);
            tblControleFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblControleFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(14);
        }

        btnSalvarFuncionario.setBackground(new java.awt.Color(0, 255, 0));
        btnSalvarFuncionario.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        btnSalvarFuncionario.setText("Salvar");
        btnSalvarFuncionario.setToolTipText("Salvar dados do funcionário");
        btnSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFuncionarioActionPerformed(evt);
            }
        });

        btnExcluirFuncionario.setBackground(new java.awt.Color(102, 102, 102));
        btnExcluirFuncionario.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        btnExcluirFuncionario.setText("Excluir");
        btnExcluirFuncionario.setToolTipText("excluir funcionário");
        btnExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFuncionarioActionPerformed(evt);
            }
        });

        lblControleFuncionarios.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        lblControleFuncionarios.setText("Controle de funcionários");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(lblControleFuncionarios)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnNovoFuncionario)
                .addGap(184, 184, 184)
                .addComponent(btnSalvarFuncionario)
                .addGap(170, 170, 170)
                .addComponent(btnExcluirFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCPFFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxCPFFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIdFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnBuscarFuncionario)
                .addGap(83, 83, 83))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblControleFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNomeFuncionario)
                        .addComponent(lblIdFuncionario)
                        .addComponent(txtCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarFuncionario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeFuncionario)
                            .addComponent(lblCPFFuncionario)
                            .addComponent(ftxCPFFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoFuncionario)
                    .addComponent(btnSalvarFuncionario)
                    .addComponent(btnExcluirFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 980, 420));

        jPanel3.setBackground(new java.awt.Color(211, 181, 143));

        lblControleClientes.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        lblControleClientes.setText("Controle de Clientes");

        lblNomeCliente.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        lblNomeCliente.setText("Nome");

        lblCPFCliente.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        lblCPFCliente.setText("CPF");

        lblCodigoCliente.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        lblCodigoCliente.setText("Código de Cliente");

        btnBuscarCliente.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnNovoCliente.setBackground(new java.awt.Color(51, 255, 153));
        btnNovoCliente.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        btnNovoCliente.setText("Novo");
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        btnSalvarCliente.setBackground(new java.awt.Color(0, 255, 0));
        btnSalvarCliente.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        btnSalvarCliente.setText("Salvar");
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });

        btnExluirCliente.setBackground(new java.awt.Color(102, 102, 102));
        btnExluirCliente.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        btnExluirCliente.setText("Excluir");
        btnExluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExluirClienteActionPerformed(evt);
            }
        });

        tblControleClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código Cliente", "Nome", "CPF", "Data Nascimento", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblControleClientes);
        if (tblControleClientes.getColumnModel().getColumnCount() > 0) {
            tblControleClientes.getColumnModel().getColumn(0).setPreferredWidth(3);
            tblControleClientes.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblControleClientes.getColumnModel().getColumn(2).setPreferredWidth(14);
            tblControleClientes.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblControleClientes.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        try {
            txtCPFCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btnNovoCliente)
                .addGap(213, 213, 213)
                .addComponent(btnSalvarCliente)
                .addGap(143, 143, 143)
                .addComponent(btnExluirCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblControleClientes)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNomeCliente)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCPFCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCodigoCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btnBuscarCliente)
                .addGap(38, 38, 38))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblControleClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCliente)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPFCliente)
                    .addComponent(lblCodigoCliente)
                    .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoCliente)
                    .addComponent(btnSalvarCliente)
                    .addComponent(btnExluirCliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, 990, 450));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Telas/ÁreaGerente.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1920, 1140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeGerenteActionPerformed

    private void btnAlterarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarGerenteActionPerformed
        // TODO add your handling code here:
        enableGerenteFields();
        btnAlterarGerente.setEnabled(false);
        btnSalvarGerente.setEnabled(true);
        btnCancelarGerente.setEnabled(true);
    }//GEN-LAST:event_btnAlterarGerenteActionPerformed

    private void btnSalvarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarGerenteActionPerformed
        // TODO add your handling code here:
        disableGerenteFields();
        Gerente gerente1 = listaGerente.get(0);
        gerente1.setNome(txtNomeGerente.getText());
        gerente1.setCPF(ftxCPFGerente.getText());
        gerente1.setEmail(txtEmailGerente.getText());
        gerente1.setSenha(txtSenhaGerente.getText());
        gerente1.setCadastroGerente(txtIdGerente.getText());
        btnAlterarGerente.setEnabled(true);
        btnSalvarGerente.setEnabled(false);
        btnCancelarGerente.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!", "Atualização de dados", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnSalvarGerenteActionPerformed

    private void btnCancelarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarGerenteActionPerformed
        // TODO add your handling code here:
        disableGerenteFields();
        loadGerenteInfo();
        btnAlterarGerente.setEnabled(true);
        btnSalvarGerente.setEnabled(false);
        btnCancelarGerente.setEnabled(false);
    }//GEN-LAST:event_btnCancelarGerenteActionPerformed

    private void btnSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFuncionarioActionPerformed
        // TODO add your handling code here:
        disableControleFuncionariosFields();
        disableControleFuncionariosButtons();
        btnNovoFuncionario.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!", "Atualização de dados", JOptionPane.INFORMATION_MESSAGE);

        carregarTabelaFuncionario();

        //btnPesquisarFuncionario.setEnabled(true);
    }//GEN-LAST:event_btnSalvarFuncionarioActionPerformed

    private void btnNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFuncionarioActionPerformed
        // TODO add your handling code here:
        //enableControleFuncionariosFields();
        cadastrosFlag="funcionario";
        disableControleFuncionariosButtons();
        btnSalvarFuncionario.setEnabled(true);
        //btnCancelarFuncionario.setEnabled(true);
        new cadastros().setVisible(true);
    }//GEN-LAST:event_btnNovoFuncionarioActionPerformed

    private void txtCodigoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoFuncionarioActionPerformed

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!", "Atualização de dados", JOptionPane.INFORMATION_MESSAGE);

        carregarTabelaCliente();
    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    private void btnExluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExluirClienteActionPerformed
        // TODO add your handling code here:
        int i = tblControleClientes.getSelectedRow();
        
                if (i>=0 && i<listaClientes.size()){
            
            listaClientes.remove(i);  
            
        }
    carregarTabelaCliente();
        
        
    
    }//GEN-LAST:event_btnExluirClienteActionPerformed

    private void btnExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFuncionarioActionPerformed
        // TODO add your handling code here:
        System.out.println(listaFuncionarios);
        int i = tblControleFuncionarios.getSelectedRow();
        System.out.println("indice da lista:"+i);
        
                if (i>=0 && i<listaFuncionarios.size()){
            
            listaFuncionarios.remove(i);  
            
        }
                System.out.println(listaFuncionarios);
    carregarTabelaFuncionario();
    }//GEN-LAST:event_btnExcluirFuncionarioActionPerformed

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
        // TODO add your handling code here:
        cadastrosFlag="cliente";
        new cadastros().setVisible(true);
        btnSalvarCliente.setEnabled(true);

    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void tblControleFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblControleFuncionariosMouseClicked
        // TODO add your handling code here:
        
        btnExcluirFuncionario.setEnabled(true);
    }//GEN-LAST:event_tblControleFuncionariosMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnBuscarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFuncionarioActionPerformed
        // TODO add your handling code here:  
        String nomePesquisado = txtNomeFuncionario.getText();
        String cpfPesquisado = ftxCPFFuncionario.getText();
        String codPesquisado = txtCodigoFuncionario.getText();
        Funcionario func;
        for(Funcionario funcionario : listaFuncionarios){
        if(funcionario.getNome().equals(nomePesquisado) || 
           funcionario.getCPF().equals(cpfPesquisado) || 
           funcionario.getCadastroFuncionario().equals(codPesquisado)){
            func = funcionario;
        txtNomeFuncionario.setText(func.getNome());
        ftxCPFFuncionario.setText(func.getCPF());
        txtCodigoFuncionario.setText(func.getCadastroFuncionario());
        int rowIndex = Integer.parseInt(func.getCadastroFuncionario());
         tblControleFuncionarios.setRowSelectionInterval(rowIndex, rowIndex);
            break;
        }
    }
    }//GEN-LAST:event_btnBuscarFuncionarioActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
                String nomePesquisado = txtNomeCliente.getText();
        String cpfPesquisado = txtCPFCliente.getText();
        String codPesquisado = txtCodCliente.getText();
        Cliente cli;
        for(Cliente cliente : listaClientes){
        if(cliente.getNome().equals(nomePesquisado) || 
           cliente.getCPF().equals(cpfPesquisado) || 
           cliente.getIdCliente().equals(codPesquisado)){
            cli = cliente;
        txtNomeCliente.setText(cli.getNome());
        txtCPFCliente.setText(cli.getCPF());
        txtCodCliente.setText(cli.getIdCliente());
        int rowIndex = Integer.parseInt(cli.getIdCliente());
         tblControleClientes.setRowSelectionInterval(rowIndex, rowIndex);
            break;
        }
    }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(areaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(areaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(areaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(areaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new areaGerente().setVisible(true);
                
            }
        });
    }
    
    public void disableGerenteFields(){
        txtNomeGerente.setEnabled(false);
        ftxCPFGerente.setEnabled(false);
        txtEmailGerente.setEnabled(false);
        txtSenhaGerente.setEnabled(false);
        txtIdGerente.setEnabled(false);
        
        lblNomeGerente.setEnabled(false);
        lblCPFGerente.setEnabled(false);
        lblEmailGerente.setEnabled(false);
        lblSenhaGerente.setEnabled(false);
        lblIdGerente.setEnabled(false);
    }
    
    public void enableGerenteFields(){
        txtNomeGerente.setEnabled(true);
        ftxCPFGerente.setEnabled(true);
        txtEmailGerente.setEnabled(true);
        txtSenhaGerente.setEnabled(true);
        txtIdGerente.setEnabled(true);
        
        lblNomeGerente.setEnabled(true);
        lblCPFGerente.setEnabled(true);
        lblEmailGerente.setEnabled(true);
        lblSenhaGerente.setEnabled(true);
        lblIdGerente.setEnabled(true);
        
    }
    
    public void disableControleFuncionariosButtons(){
        btnNovoFuncionario.setEnabled(false);
        btnSalvarFuncionario.setEnabled(false);
        //btnCancelarFuncionario.setEnabled(false);
        btnExcluirFuncionario.setEnabled(false);
        //btnPesquisarFuncionario.setEnabled(false);
        btnBuscarFuncionario.setEnabled(false);

    }
    
    public void disableControleFuncionariosFields(){
        //NUNCA DEIXE O TXTCODIGOFUNCIONARIO COMO ENABLED=TRUE. CASO ISSO SEJA FEITO E O ÍNDICE DO FUNCIONÁRIO SEJA MUDADO PARA UM VALOR JÁ EXISTENTE, ENTÃO O SISTEMA QUEBRA
        txtNomeFuncionario.setEnabled(false);
        ftxCPFFuncionario.setEnabled(false);
        //txtEmailFuncionario.setEnabled(false);
        //txtSenhaFuncionario.setEnabled(false);
        txtCodigoFuncionario.setEnabled(false);
        
        lblNomeFuncionario.setEnabled(false);
        lblCPFFuncionario.setEnabled(false);
        //lblEmailFuncionario.setEnabled(false);
        //lblSenhaFuncionario.setEnabled(false);
        lblIdFuncionario.setEnabled(false);
        
    }
    
    public void enableControleFuncionariosFields(){
        //NUNCA DEIXE O TXTCODIGOFUNCIONARIO COMO ENABLED=TRUE. CASO ISSO SEJA FEITO E O ÍNDICE DO FUNCIONÁRIO SEJA MUDADO PARA UM VALOR JÁ EXISTENTE, O SISTEMA QUEBRA
        txtNomeFuncionario.setEnabled(true);
        ftxCPFFuncionario.setEnabled(true);
        //txtEmailFuncionario.setEnabled(true);
        //txtSenhaFuncionario.setEnabled(true);
        txtCodigoFuncionario.setEnabled(false);//FALSE
        
        lblNomeFuncionario.setEnabled(true);
        lblCPFFuncionario.setEnabled(true);
        //lblEmailFuncionario.setEnabled(true);
        //lblSenhaFuncionario.setEnabled(true);
        lblIdFuncionario.setEnabled(true);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarGerente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarFuncionario;
    private javax.swing.JButton btnCancelarGerente;
    private javax.swing.JButton btnExcluirFuncionario;
    private javax.swing.JButton btnExluirCliente;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JButton btnNovoFuncionario;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.JButton btnSalvarFuncionario;
    private javax.swing.JButton btnSalvarGerente;
    private javax.swing.JFormattedTextField ftxCPFFuncionario;
    private javax.swing.JFormattedTextField ftxCPFGerente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAreaGerente;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCPFCliente;
    private javax.swing.JLabel lblCPFFuncionario;
    private javax.swing.JLabel lblCPFGerente;
    private javax.swing.JLabel lblCodigoCliente;
    private javax.swing.JLabel lblControleClientes;
    private javax.swing.JLabel lblControleFuncionarios;
    private javax.swing.JLabel lblEmailGerente;
    private javax.swing.JLabel lblIdFuncionario;
    private javax.swing.JLabel lblIdGerente;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeFuncionario;
    private javax.swing.JLabel lblNomeGerente;
    private javax.swing.JLabel lblSenhaGerente;
    private javax.swing.JTable tblControleClientes;
    private javax.swing.JTable tblControleFuncionarios;
    private javax.swing.JFormattedTextField txtCPFCliente;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtCodigoFuncionario;
    private javax.swing.JTextField txtEmailGerente;
    private javax.swing.JTextField txtIdGerente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtNomeGerente;
    private javax.swing.JTextField txtSenhaGerente;
    // End of variables declaration//GEN-END:variables

}
