/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Gerente;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Yuri
 */
public class cadastarGerente extends javax.swing.JFrame {
    static ArrayList<Gerente> listaGerente = new ArrayList();


    /**
     * Creates new form cadastarGerente
     */
    public cadastarGerente() {
        initComponents();
        getRootPane().setDefaultButton(btnSalvarGerente);
        setLocationRelativeTo(null);
        limparCampos();
    }
    public void limparCampos(){
        txtNomeGerente.setText("");
        txtCPFGerente.setText("");
        txtEmailGerente.setText("");
        txtSenhaGerente.setText("");
        txtCadastroGerente.setText("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeGerente = new javax.swing.JLabel();
        lblCPFGerente = new javax.swing.JLabel();
        lblEmailGerente = new javax.swing.JLabel();
        lblSenhaGerente = new javax.swing.JLabel();
        lblCadastroGerente = new javax.swing.JLabel();
        txtNomeGerente = new javax.swing.JTextField();
        txtCPFGerente = new javax.swing.JFormattedTextField();
        txtEmailGerente = new javax.swing.JTextField();
        txtSenhaGerente = new javax.swing.JTextField();
        txtCadastroGerente = new javax.swing.JTextField();
        btnSalvarGerente = new javax.swing.JButton();
        btnCancelarGerente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Gerentes");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/customer_person_people_man_you_1625.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomeGerente.setText("Nome");

        lblCPFGerente.setText("CPF");

        lblEmailGerente.setText("E-mail");

        lblSenhaGerente.setText("senha");

        lblCadastroGerente.setText("Cadastro Gerente");

        txtNomeGerente.setToolTipText("Insira o nome do gerente");

        try {
            txtCPFGerente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFGerente.setToolTipText("inserir o CPF do gerente");

        txtEmailGerente.setToolTipText("Inserir o e-mail do gerente");

        txtSenhaGerente.setToolTipText("definir uma senha para o gerente");

        txtCadastroGerente.setToolTipText("Inserir o cadastro do gerente");

        btnSalvarGerente.setBackground(new java.awt.Color(0, 255, 0));
        btnSalvarGerente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalvarGerente.setText("Salvar");
        btnSalvarGerente.setToolTipText("salvar dados do gerente");
        btnSalvarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarGerenteActionPerformed(evt);
            }
        });

        btnCancelarGerente.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelarGerente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelarGerente.setText("Cancelar");
        btnCancelarGerente.setToolTipText("cancelar operação");
        btnCancelarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarGerenteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Cadastro de Gerentes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomeGerente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmailGerente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailGerente, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCadastroGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCadastroGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCPFGerente)
                .addGap(18, 18, 18)
                .addComponent(txtCPFGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(lblSenhaGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaGerente)
                .addGap(231, 231, 231))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnSalvarGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarGerente)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNomeGerente)
                        .addComponent(lblEmailGerente)
                        .addComponent(lblCadastroGerente)
                        .addComponent(txtEmailGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCadastroGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNomeGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFGerente)
                    .addComponent(lblSenhaGerente)
                    .addComponent(txtCPFGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenhaGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarGerente)
                    .addComponent(btnCancelarGerente))
                .addGap(57, 57, 57))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 670, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarGerenteActionPerformed
        // TODO add your handling code here:
        if (txtNomeGerente.getText().equals("") || txtCPFGerente.getText().equals("") ||
            txtEmailGerente.getText().equals("") || txtSenhaGerente.getText().equals("")
                || txtCadastroGerente.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Todos os campos devem ser inseridos!", "Mensagem",JOptionPane.PLAIN_MESSAGE);
        }else{
        String nome = txtNomeGerente.getText();
        String cpf = txtCPFGerente.getText();
        String email = txtEmailGerente.getText();
        String senha = txtSenhaGerente.getText();
        String idGerente = txtCadastroGerente.getText();
        
        Gerente gerente = new Gerente(nome,cpf,email,senha,idGerente);
        
                    JOptionPane.showMessageDialog(null,"Gerente cadastrado com sucesso!", "Mensagem",JOptionPane.PLAIN_MESSAGE);
        listaGerente.add(gerente);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnSalvarGerenteActionPerformed

    private void btnCancelarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarGerenteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastarGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastarGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastarGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastarGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastarGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarGerente;
    private javax.swing.JButton btnSalvarGerente;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCPFGerente;
    private javax.swing.JLabel lblCadastroGerente;
    private javax.swing.JLabel lblEmailGerente;
    private javax.swing.JLabel lblNomeGerente;
    private javax.swing.JLabel lblSenhaGerente;
    private javax.swing.JFormattedTextField txtCPFGerente;
    private javax.swing.JTextField txtCadastroGerente;
    private javax.swing.JTextField txtEmailGerente;
    private javax.swing.JTextField txtNomeGerente;
    private javax.swing.JTextField txtSenhaGerente;
    // End of variables declaration//GEN-END:variables
}
