/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Carrinho;
//import static classes.Carrinho.listaCarrinho;
import static classes.Carrinho.listaProdutos;
import classes.Cliente;
import static classes.Cliente.index_cliente;
import static classes.Cliente.listaClientes;
import classes.Funcionario;
import static classes.Funcionario.index_func;
import static classes.Funcionario.listaFuncionarios;
import classes.Gerente;
import classes.Pagamento;
import classes.Pedido;
import classes.Produto;
import static classes.Usuario.user;
//import static classes.Usuario.historicoCarrinhosTotais;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static telas.Menu.historicoCarrinhosTotais;
//import static telas.Menu.user;
import static telas.cadastarGerente.listaGerente;
import static telas.verCarrinho.aux;

/**
 *
 * @author Yuri
 */
public class telaPagamento extends javax.swing.JFrame {
    Pedido pedido = new Pedido();
    Pagamento pagamento = new Pagamento();

    /**
     * Creates new form telaPagamento
     */
    public telaPagamento() {
        initComponents();
        setLocationRelativeTo(null);
        newCarregarInfoPagamento();
        
        

    }
    
    public void newCarregarInfoPagamento(){
        Carrinho carrinhoSalvo = aux.get(0);
        if(rdbPix.isSelected()){
            double desconto = 0.95*carrinhoSalvo.getTotal();
            txtValorTotal.setText(String.format("%.2f", desconto));
            pagamento.setFormaPagamento("Pix");
        }else if(rdbBoleto.isSelected()){
        txtValorTotal.setText(String.format("%.2f", carrinhoSalvo.getTotal()));
        pagamento.setFormaPagamento("Boleto");

        }
        txtNumCarrinho.setText(String.valueOf(carrinhoSalvo.getNumCarrinho()));
        txtProdutos.setText(carrinhoSalvo.mostarProdutos(carrinhoSalvo.itensNoCarrinho));
        carrinhoSalvo.setPagamento(pagamento);
        System.out.println("Carrinho Salvo tem o pagamento de:"+pagamento.getFormaPagamento());
        System.out.println("Carrinho salvo tem o pedido de:"+pedido.getCodPedido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblPagamento = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        lblFormaPagamento = new javax.swing.JLabel();
        rdbBoleto = new javax.swing.JRadioButton();
        rdbPix = new javax.swing.JRadioButton();
        lblNumCarrinho = new javax.swing.JLabel();
        txtNumCarrinho = new javax.swing.JTextField();
        lblProduto = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProdutos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela pagamento");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/sacola.png")).getImage());

        jPanel2.setBackground(new java.awt.Color(123, 57, 23));

        jPanel1.setBackground(new java.awt.Color(211, 181, 143));

        lblPagamento.setFont(new java.awt.Font("Old London", 0, 24)); // NOI18N
        lblPagamento.setText("Pagamento");

        lblValorTotal.setText("Valor Total");

        txtValorTotal.setToolTipText("valor total");

        lblFormaPagamento.setText("Forma de pagamento");

        buttonGroup1.add(rdbBoleto);
        rdbBoleto.setSelected(true);
        rdbBoleto.setText("Boleto");
        rdbBoleto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbBoletoMouseClicked(evt);
            }
        });

        buttonGroup1.add(rdbPix);
        rdbPix.setText("Pix");
        rdbPix.setToolTipText("Pague no pix para 5% de desconto!");
        rdbPix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbPixMouseClicked(evt);
            }
        });

        lblNumCarrinho.setText("Número do carrinho");

        txtNumCarrinho.setToolTipText("número do carrinho");

        lblProduto.setText("Produtos");

        btnPagar.setBackground(new java.awt.Color(0, 204, 0));
        btnPagar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Desconto de 5% no pix!");

        txtProdutos.setColumns(20);
        txtProdutos.setRows(5);
        jScrollPane1.setViewportView(txtProdutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPagar)
                    .addComponent(lblFormaPagamento))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(btnCancelar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(rdbBoleto)
                            .addGap(33, 33, 33)
                            .addComponent(rdbPix)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProduto)
                    .addComponent(lblValorTotal)
                    .addComponent(lblNumCarrinho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPagamento)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(332, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtValorTotal)
                        .addComponent(txtNumCarrinho))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblValorTotal)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNumCarrinho)
                        .addGap(18, 18, 18)
                        .addComponent(lblProduto)
                        .addGap(99, 99, 99))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaPagamento)
                    .addComponent(rdbBoleto)
                    .addComponent(rdbPix))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagar)
                    .addComponent(btnCancelar))
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtNumCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        LocalDate today = LocalDate.now();

        // Define a date format (e.g., "dd/MM/yyyy")
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Convert the date to a string
        String formattedDate = today.format(formatter);
        newCarregarInfoPagamento();
        historicoCarrinhosTotais+=1;
        System.out.println(historicoCarrinhosTotais);
            if(listaProdutos.size()>0){
                if(user.equals("cliente")){
                Cliente cliente = listaClientes.get(index_cliente);
                ArrayList listaCarrinhoDoCliente = cliente.getListaCarrinho();
                int indexCarrinho = listaCarrinhoDoCliente.size();

                // Clone the ArrayList
                ArrayList<Produto> clonedList = (ArrayList<Produto>) listaProdutos.clone();
                Carrinho carrinho1 = new Carrinho(indexCarrinho,formattedDate,clonedList);
                carrinho1.setTotal(Double.parseDouble(txtValorTotal.getText()));
                carrinho1.setPagamento(pagamento);
                cliente.addCarrinhoLista(carrinho1);
                //pagamento.setPedido(pedido);
                //pedido.setCodPedido(historicoCarrinhosTotais);
                //pagamento.setPedido(pedido);
                pedido.setCodPedido(historicoCarrinhosTotais);
                pagamento.setPedido(pedido);
                carrinho1.setPagamento(pagamento);

                    
                }
                if(user.equals("funcionario")){
                    Funcionario funcionario = listaFuncionarios.get(index_func);
                    ArrayList listaCarrinhoDoFuncionario = funcionario.getListaCarrinhoFuncionario();
                    int indexCarrinho = listaCarrinhoDoFuncionario.size();
                    
                    ArrayList<Produto> clonedList = (ArrayList<Produto>) listaProdutos.clone();
                    Carrinho carrinho2 = new Carrinho(indexCarrinho,formattedDate,clonedList);
                    carrinho2.setTotal(Double.parseDouble(txtValorTotal.getText()));
                    carrinho2.setPagamento(pagamento);

                    funcionario.addListaCarrinhosFuncionarios(carrinho2);
                                                //pagamento.setPedido(pedido);
                    pedido.setCodPedido(historicoCarrinhosTotais);
                    pagamento.setPedido(pedido);
                    carrinho2.setPagamento(pagamento);
                    
                }
                    if(user.equals("gerente")){
                    Gerente gerente = listaGerente.get(0);
                    ArrayList listaCarrinhoDoGerente = gerente.getListaCarrinhoGerente();
                    int indexCarrinho = listaCarrinhoDoGerente.size();
                    
                    ArrayList<Produto> clonedList = (ArrayList<Produto>) listaProdutos.clone();
                    Carrinho carrinho2 = new Carrinho(indexCarrinho,formattedDate,clonedList);
                    carrinho2.setTotal(Double.parseDouble(txtValorTotal.getText()));
                        System.out.println("Lista de carrinhos do gerente é de tamanho:"+gerente.getListaCarrinhoGerente().size());
                    carrinho2.setPagamento(pagamento);


                    gerente.addListaCarrinhosGerente(carrinho2);
                        System.out.println("Adicionado. Tamanho agora é:"+gerente.getListaCarrinhoGerente());
                    pedido.setCodPedido(historicoCarrinhosTotais);
                    pagamento.setPedido(pedido);
                    carrinho2.setPagamento(pagamento);
                    
                }
            System.out.println();

            listaProdutos.clear();
            aux.clear();
            System.out.println("Adicionado ao Histórico!");   

        }
        JOptionPane.showMessageDialog(null,"Compra realizada com sucesso!","Notificação de compra!",JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);

    
        //listaProdutos.clear();
    }//GEN-LAST:event_btnPagarActionPerformed

    private void rdbPixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbPixMouseClicked
        // TODO add your handling code here:
        newCarregarInfoPagamento();
    }//GEN-LAST:event_rdbPixMouseClicked

    private void rdbBoletoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbBoletoMouseClicked
        // TODO add your handling code here:
        newCarregarInfoPagamento();
    }//GEN-LAST:event_rdbBoletoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFormaPagamento;
    private javax.swing.JLabel lblNumCarrinho;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JRadioButton rdbBoleto;
    private javax.swing.JRadioButton rdbPix;
    private javax.swing.JTextField txtNumCarrinho;
    private javax.swing.JTextArea txtProdutos;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
